<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.sap.cds</groupId>
  <artifactId>sap-document-ai</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>sap-document-ai</name>

  <properties>
    <jdk.version>17</jdk.version>
    <cds.services.version>4.6.0</cds.services.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <generation-package>com.sap.cds.feature.documentai.generated</generation-package>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.sap.cds</groupId>
        <artifactId>cds-services-bom</artifactId>
        <version>${cds.services.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.sap.cds</groupId>
        <artifactId>cds-feature-attachments</artifactId>
        <version>1.5.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-services-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds4j-core</artifactId>
      <version>${cds.services.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>6.2.6</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-feature-attachments</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.11.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>5.12.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <version>4.2.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.26.3</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.1</version>
        <configuration>
          <release>${jdk.version}</release>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.sap.cds</groupId>
        <artifactId>cds-maven-plugin</artifactId>
        <version>${cds.services.version}</version>
        <executions>
          <execution>
            <id>cds.build</id>
            <goals>
              <goal>cds</goal>
            </goals>
            <configuration>
              <commands>
                <command>build --for java --src ${project.basedir}/src/main/resources/cds/com.sap.cds/sap-document-ai --dest ${project.basedir}/gen/srv</command>
              </commands>
            </configuration>
          </execution>

          <execution>
            <id>cds.generate</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <basePackage>${generation-package}.cds4j</basePackage>
              <csnFile>${project.basedir}/gen/srv/src/main/resources/edmx/csn.json</csnFile>
              <includes>
                <include>sap.document.ai.**</include>
              </includes>
            </configuration>
          </execution>

        </executions>
      </plugin>
    </plugins>
  </build>
</project>
