spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

cds:
  model:
    include-ui-annotations: true
  ai:
    core:
      resourceGroup: ${CDS_AICORE_TEST_RESOURCE_GROUP:cap-java-ai-default}
      maxRetries: 15
  security:
    mock:
      users:
        test-user:
          password: pass
        tenant-a-user:
          password: pass
          tenant: tenant-a
        tenant-b-user:
          password: pass
          tenant: tenant-b
        admin-user:
          password: pass
          roles:
            - admin
