name: CI - MAIN

env:
  MAVEN_VERSION: '3.9.15'

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  blackduck:
    name: Blackduck Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Scan With Black Duck
        uses: cap-java/.github/actions/scan-with-blackduck@296573b55e906f5c77a1855bcfe4285cbbc5cac4 # main
        with:
          blackduck_token: ${{ secrets.BLACK_DUCK_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          maven-version: ${{ env.MAVEN_VERSION }}
          project-name: com.sap.cds.cds-ai
          included-modules: cds-feature-ai-core,cds-feature-recommendations,cds-starter-ai
          scan_mode: FULL

  build-and-test:
    uses: ./.github/workflows/pipeline.yml
    permissions:
      contents: read
      security-events: write
      actions: read
      packages: read
    secrets: inherit
